### ISSUE TITLE
tons-o-warnings in pytest 4.1.0+

### ISSUE THREAD

**Issue by okken** [hackebrot/pytest-emoji#3]
Lots of these:
PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.

**Comment by okken** [comment]
Tried to fix on a fork. I have a workaround, but still working on tests.

**Comment by hackebrot** [comment]
Awesome, thanks for looking into it @okken! 🙇

**Comment by hackebrot** [comment]
See #4

**Comment by nicoddemus** [comment]
This can be closed now, I assume?

**Comment by okken** [comment]
yes. bug fixed.

**Comment by okken** [comment]
Well. Re-opened the issue. I think I may have closed it too soon. 
Questions about open source process:
1. This fix depends on a feature of pytest not yet released. Is it fair to close it?
2. The PyPI version still has the bug. Do you close the bug before or after pushing to PyPI?

**Comment by okken** [comment]
Doh! nevermind about #1. I hadn't read the code yet. 
The fix doesn't use the new pytest API.

However, this raises another question:
3. Should the issue remain open until a new pytest version is out where the fix can use the new api?

**Comment by nicoddemus** [comment]
I guess it varies, but on pytest we close the issue as soon as it is merged on the repository, regardless if a new release with the fix has been made.
